version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    ports:
      - "80:80"