services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  backend-test:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    depends_on:
      redis:
        condition: service_healthy
    command: ["go", "test", "-v", "./..."]

  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  integration-test:
    image: curlimages/curl:latest
    depends_on:
      backend:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Testing health endpoint...' &&
        curl -f http://backend:8080/health &&
        echo 'Health check passed!' &&
        echo 'Testing screenshot endpoint...' &&
        curl -X POST http://backend:8080/api/screenshot \
          -H 'Content-Type: application/json' \
          -d '{\"url\":\"https://example.com\"}' \
          --max-time 30 &&
        echo 'Screenshot test passed!' &&
        echo 'Testing history endpoint...' &&
        curl -f http://backend:8080/api/history &&
        echo 'History test passed!'
      "